version: '3.9'

services:

  pattern_database:
    container_name: pattern_database
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    # command: sh -c "rm -rf /var/lib/postgresql/d1/"
    volumes:
      - ./pg_data:/var/lib/postgresql

    # pattern_backend:
    #   container_name: pattern_backend
    #   restart: always
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   depends_on:
    #     - pattern_database
    #   env_file:
    #     - ./.env

    # pattern_nginx:
    #   image: nginx:1.19.3
    #   container_name: pattern_nginx
    #   restart: always
    #   ports:
    #     - '80:80'
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
