version: '3.9'

services:

  database:
    container_name: database
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    networks:
      - djangonetwork
    volumes:
      - ./data/:/var/lib/

  backend:
    container_name: backend_test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - djangonetwork
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    container_name: nginx_test
    restart: always
    ports:
      - '80:80'
    # volumes:
    #   - nuxt_value:/usr/share/nginx/html/
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #   - static_value:/var/html/static/
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  database_value:
