# Generated by Django 4.2.4 on 2023-08-18 22:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[app.models.phone_validate], verbose_name='Телефон'),
        ),
    ]
