# Generated by Django 4.2.4 on 2024-04-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.IntegerField(verbose_name='Вакансия')),
                ('vacancy_name', models.CharField(max_length=50, verbose_name='Название')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50, verbose_name='Навык')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='Уровень владения')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skills')),
            ],
            options={
                'verbose_name': 'Уровень владения',
                'verbose_name_plural': 'Уровень владения',
                'db_table': 'level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Candidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('adress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('skill_name', models.CharField(max_length=50, verbose_name='Навык')),
                ('level', models.CharField(max_length=50, verbose_name='Уровень владения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'db_table': 'candidats',
                'managed': True,
            },
        ),
    ]
