# Generated by Django 4.2.4 on 2024-04-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='user_id',
            new_name='user',
        ),
    ]
