# Generated by Django 4.2.4 on 2024-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_id_vacancy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_id',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Вакансия'),
        ),
    ]
