# Generated by Django 4.2.4 on 2024-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_vacancy_vacancy_id_alter_vacancy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidats',
            old_name='vacancy',
            new_name='vacancy_id',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='skill',
            new_name='skills_id',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='vacancy',
            new_name='vacancy_id',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
