# Generated by Django 4.2.4 on 2024-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_vacancy_candidats_vacancy_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidats',
            old_name='skill_name',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='candidats',
            old_name='vacancy_id',
            new_name='vacancy',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='skills_id',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='vacancy_id',
            new_name='vacancy',
        ),
    ]
