# Generated by Django 4.2.4 on 2024-04-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vacancy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='app.skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.vacancy', verbose_name='Вакансия'),
        ),
    ]
