# Generated by Django 4.2.4 on 2024-04-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_level_skills_alter_skills_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='app.vacancy', verbose_name='Вакансии'),
        ),
        migrations.AlterField(
            model_name='level',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='app.skills'),
        ),
    ]
